services:
  ecma262-ast:
    build:
      context: .
      secrets:
        - github_token
    image: tontonialberto/ecma262-ast
    command: ["$ECMA262_VERSION"]
    volumes:
      - ./out/${ECMA262_VERSION}/esmeta-logs:/esmeta/logs/extract
      - ./out/${ECMA262_VERSION}/normalized-asts:/ecma262-projectional-editor-scripts/spec-manipulator/out
      - ./out/${ECMA262_VERSION}/biblio:/esmeta/ecma262/biblio
secrets:
  github_token:
    file: ./github_token